"""`wiki-index-render` rendering primitives.

Generates `<vault>/index.md` from the `index_meta` VIEW. Preserves
`<!-- BEGIN-CUSTOM:name -->...<!-- END-CUSTOM:name -->` blocks across
re-renders (ADR-002 §D8 — operator-owned prose inside Class B file).
"""

from __future__ import annotations

import os
import re
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING

from scripts.wiki_index.layout import VAULT_TIER_PROJECT

if TYPE_CHECKING:
    from scripts.wiki_index.repository import IndexRepository

_CUSTOM_BLOCK_RE = re.compile(
    r"<!--\s*BEGIN-CUSTOM:([a-z0-9-]+)\s*-->(.*?)<!--\s*END-CUSTOM:\1\s*-->",
    re.DOTALL,
)


def extract_custom_sections(existing_md: str) -> dict[str, str]:
    """Find `<!-- BEGIN-CUSTOM:name -->...<!-- END-CUSTOM:name -->` blocks.

    Returns `{name: full_block_text}` where full_block_text includes both markers.
    """
    out: dict[str, str] = {}
    for m in _CUSTOM_BLOCK_RE.finditer(existing_md):
        name = m.group(1)
        out[name] = m.group(0)
    return out


def render_index(
    repo: "IndexRepository",
    vault_id: str,
    *,
    preserve_custom: dict[str, str] | None = None,
) -> str:
    """Render `index.md` content from the `index_meta` VIEW for one vault.

    `preserve_custom`: blocks to inject at the end (after auto-generated
    sections). Order preserved by insertion order.
    """
    # Access connection directly via SQLite repo (defined in subclass);
    # use the search-style approach.
    from scripts.wiki_index.sqlite_repository import SQLiteRepository
    if not isinstance(repo, SQLiteRepository):
        raise NotImplementedError("render_index supports SQLiteRepository only")

    rows = repo._connect().execute(
        "SELECT slug, project, kind, title, tldr "
        "FROM index_meta WHERE vault_id = ? "
        "ORDER BY project, kind, slug",
        (vault_id,),
    ).fetchall()

    lines: list[str] = [
        f"# Index — {vault_id}",
        "",
        "<!-- AUTO-GENERATED by wiki-index-render. Custom sections marked "
        "with BEGIN-CUSTOM/END-CUSTOM are preserved across re-renders. -->",
        "",
    ]

    # Group by (project, kind)
    by_project: dict[str, dict[str, list[tuple[str, str, str | None]]]] = {}
    for r in rows:
        proj = r["project"] or VAULT_TIER_PROJECT
        by_project.setdefault(proj, {}).setdefault(r["kind"], []).append(
            (r["slug"], r["title"], r["tldr"])
        )

    for proj in sorted(by_project):
        lines.append(f"## Project: `{proj}`")
        lines.append("")
        for kind in sorted(by_project[proj]):
            entries = by_project[proj][kind]
            lines.append(f"### {kind.capitalize()}s ({len(entries)})")
            lines.append("")
            for slug, title, tldr in entries:
                tldr_part = f" — {tldr}" if tldr else ""
                lines.append(f"- [[{slug}|{title}]]{tldr_part}")
            lines.append("")

    if preserve_custom:
        lines.append("---")
        lines.append("")
        for name in preserve_custom:
            lines.append(preserve_custom[name])
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def atomic_write(path: Path, content: str) -> None:
    """Write `content` to `path` atomically (tempfile + os.rename).

    `os.rename` is atomic on POSIX within the same filesystem; macOS APFS
    preserves the guarantee within one volume.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    # tempfile in same dir → same filesystem → rename is atomic
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=".tmp-")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
        os.rename(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def auto_shard(content: str, max_pages: int = 200) -> dict[str, str]:
    """Stub for shard logic. Phase 3a returns a single file; sharding triggers
    in task-001-33 when benchmark vaults exceed `max_pages`."""
    _ = max_pages  # accepted for forward-compat
    return {"index.md": content}
